### ISSUE TITLE
unlease and lease both negative

### ISSUE THREAD

**Issue by br0x** [deemru/w8io#1]
Its quite confusing that both transaction types - lease and unlease - have negative sign
<img width="1149" alt="Screen Shot 2019-04-01 at 19 57 18" src="https://user-images.githubusercontent.com/1069223/55345401-7418aa80-54b8-11e9-8aaa-06ab538d9812.png">

**Comment by deemru** [comment]
ok, fixed: https://github.com/deemru/w8io/commit/caf20f9ceff44477a66d97733278a6a6d886956f#diff-828e0013b8f3bc1bb22b4f57172b019dR370
