### ISSUE TITLE
Need small fix

### ISSUE THREAD

**Issue by username1565** [deemru/w8io#10]
Un-leasing, this is outgoing transfer, not incoming:
[![изображение](https://user-images.githubusercontent.com/39200328/69503652-9ddd8080-0f24-11ea-8afe-f3cfd3b3d8c9.png)](https://w8io.ru/WAVES_ADDRESS/)

Just reverse this bracket quote.

**Comment by deemru** [comment]
This is a misunderstanding, the actual point is:
- `<` = incoming transaction
- `>` = outgoing transaction

If someone did unlease from a node, it is someone's action, not the node action, so it cannot be `>`.

Another way of thinking is to imagine whos signature on a transaction. If it is not you then it is always incoming '<' transaction.

**Comment by username1565** [comment]
If someone cansel his leasing, then `generating balance` on the node is decreasing, so this transfer is a outgoing transaction from the generating balance of the `node-address`, and node cann't `do mining`, using this `unleasing waves`.
This is the main point, why I think,
that will be better to mark `un-leasing transactions` as `outgoing transactions`.
Yes, this is not depending from `node-owner`, and he don't sign this transactions,
but maybe this `un-leasing` is a result of strategy of his business, and in this case, the node owner can take some decisions to protect his business, if he sees that the balance on the node is reduced due to `outgoing transactions` to balances of `his creditors`, who give their WAVES to him `in leasing`.

**Comment by deemru** [comment]
> but maybe this un-leasing is a result of strategy of his business

Then he should add this case to his code appropriate.

I do not see why it should change the global and very straightforward logic of w8io.

**Comment by username1565** [comment]
Ну тебя и развезло, из-за одной скобки.
