### ISSUE TITLE
Can you add an ability to see last transactions by AssetID?

### ISSUE THREAD

**Issue by username1565** [deemru/w8io#12]
Hello, can you add the ability to see last transactions by Asset ID?
For example, I want to see all last transactions of exchange Official USD token - WUSD: https://dev.pywaves.org/assets/Ft8X1v1LTa1ABafufpaCWyVj8KkaxUWE6xBhW6sNFJck
for which, trading was been closed, after SCAM the coinomat.com,
and closed, at April 2020, without any progress, up to current moment.

https://coincodex.com/crypto/wusd/?period=ALL

**Comment by deemru** [comment]
https://w8io.ru/t/f/Ft8X1v1LTa1ABafufpaCWyVj8KkaxUWE6xBhW6sNFJck
