### ISSUE TITLE
w8_updater.php (branch renew) not running for me

### ISSUE THREAD

**Issue by WavescapTorben** [deemru/w8io#13]
Hi, thanks for this great lib!
When I am trying to run the new w8_updater.php from renew branch I am getting following error:
PHP Fatal error:  Uncaught Error: Call to undefined function w8io\wk() in /w8_updater.php:12
I am running PHP 7.3 and the old master branch (release Jan 17, 2020) is working fine with it.
I installed by using: composer install

**Comment by deemru** [comment]
Hello, there were some changes in config.php, the current config sample is outdated.

I`ll try to fix that.

**Comment by deemru** [comment]
@WavescapTorben now should work out of the box, confirm and close please

**Comment by deemru** [comment]
@WavescapTorben and almost forgot, the minimum version is PHP 7.4

**Comment by WavescapTorben** [comment]
Yes, updated w8io and PHP to v7.4 and its running fast! Thanks for your great work)
