### ISSUE TITLE
Can you add headers?

### ISSUE THREAD

**Issue by ghost** [deemru/w8io#2]
Can you kindly add column headers to the table displayed here: https://w8io.ru/GENERATORS?
Also add a legend that explains what's the difference between o and O when a block is mined?

**Comment by deemru** [comment]
> add column headers to the table

Why?

> add a legend that explains what's the difference between o and O

Looks self-explanatory to me:
- o - single block
- O - more than one blOck
- **O** - more than average bl**O**cks

**Comment by ghost** [comment]
> Why

(Disclaimer: this is not an issue, more a suggestion)

Readability/user friendly; while its clear that 3P is the node address, some visitors wouldn't know what are the other numbers (leased waves, performance ration etc.) For example what is 184.3887 and (251)?

 1) 3P2HNUd5VUPLMQkJmctTPEeeHumiPN2GkTb (wavesgo)                         7'707'172  17.78%  OOOOOOOOOOOOOOOOOOOOOO.OoOoOoOOOOoOOOOOOOOoOOOOO.OOOoOOOoOOOOOOOO.OooOOOoOoOOOOO   184.38870000 (251)

**Comment by deemru** [comment]
> For example what is 184.3887 and (251)?

184.3887 Waves earned in 251 mined blocks.

--

There is no reason to overload excessive information, the GENERATORS page is technical one. And the w8io project is the same. I don't have time and reasons to make it beautiful or user friendly. It is for pros.

Feel free to ask questions but there would be no legend.

**Comment by ghost** [comment]
Ok, thank you, fair enough.
