### ISSUE TITLE
Update pay if already pay.

### ISSUE THREAD

**Issue by username1565** [deemru/w8io#3]
I have the node with address 3P68Vpfa8UqhB1AGtXNSknYv1qMiJiCgXMj
and some my leasings from address 3PPTYsB78vQ5B7to1PHmgW6Bqdkkfavdcjn
I did found two blocks, and I want to see for who and how much need to pay for this block.
I go here: https://w8io.ru/3P68Vpfa8UqhB1AGtXNSknYv1qMiJiCgXMj/pay/1150000/5000000
And I see some value `0.31120000 Waves`.
Then, I did pay from my node for the leaser, after found first block.
You can see the transfer here: https://w8io.ru/3P68Vpfa8UqhB1AGtXNSknYv1qMiJiCgXMj
`2019.08.23 23:14 (1674207) (transfer) 3P68Vpfa8UqhB1AGtXNSknYv1qMiJiCgXMj -> 3PPTYsB78vQ5B7to1PHmgW6Bqdkkfavdcjn -0.31120000 Waves (0.00100000 Waves fee)`
But, after this payment, I still see those value there.
And now, my debt for myself is not correct displaying.

Something wrong. Just subtract already outgoing transfers for leasers, there.

**Comment by deemru** [comment]
It is not possible to understand as a script the node's owner motivation of transfer transactions, so it cannot be done.

**Comment by username1565** [comment]
Is there any way, to calculate the exact values for future payments for each leaser,
using your block-explorer, or some another tools, like the some formula?
I see they http://h2ox.io/ paying for leasers after generation each block in mainnet.

**Comment by deemru** [comment]
It looks like you are using ‘pay’ tool wrong.

You have to enter a range which you want to get payments for.

So, for example, first time you use pay/1150000/1159999 then next time you should use pay/1160000/1169999 etc.
