### ISSUE TITLE
Add TXID in transaction list.

### ISSUE THREAD

**Issue by username1565** [deemru/w8io#4]
Hello!
On the page https://w8io.ru/WAVESADDRESS/
There is available the transactions history.
But, there is no any TXID and the link on TXID.
So, will be better to show this info, and add the URL for TXID.
Something, like this: https://wavesblockexplorer.com/#!/tx/DvsqoyTaDyZEAxXsFCwMa1ZjToCYTkRsty6j8464MdCJ
if your explorer not supporting show info by TXID,
or will be better to implement the supporting this.

Best regards.

**Comment by deemru** [comment]
i want it too, but cannot decide where to place the link better? on a timestamp?

**Comment by username1565** [comment]
Yes. `Date-time -> link -> transaction ID`.
Also, near this link, you place the separate link, with javascript function to copy `txid`.
For example [copy txid](https://www.w3schools.com/bootstrap/bootstrap_ref_comp_glyphs.asp) -> glyphicon glyphicon-copy -> [copied!](https://www.w3schools.com/howto/howto_js_copy_clipboard.asp)
and in the title tooltip can be full txid.

Example:
```html
<a href="https://wavesblockexplorer.com/#!/tx/DvsqoyTaDyZEAxXsFCwMa1ZjToCYTkRsty6j8464MdCJ">2019.09.06 18:33</a>
<a href="javascript:void(0)" onclick="function_to_copy_txid('DvsqoyTaDyZEAxXsFCwMa1ZjToCYTkRsty6j8464MdCJ');" title="DvsqoyTaDyZEAxXsFCwMa1ZjToCYTkRsty6j8464MdCJ">Copy TXID.</a>
```

**Comment by username1565** [comment]
I see transactions is available here: https://w8io.ru/tx/DvsqoyTaDyZEAxXsFCwMa1ZjToCYTkRsty6j8464MdCJ
But on that links, where timestamp - just a numbers, and nothing to open.

**Comment by deemru** [comment]
it works now

**Comment by username1565** [comment]
Hm... I still see the numbers when link is on hover of mouse cursor.
Then, onclick, I see redirect is working.
But, I think, this number need to replace to txid directly, without redirect,
because maybe, txid's there is in some associative array,
and if number of visitors will be so much, then this can working incorrectly, no?

**Comment by deemru** [comment]
no, these numbers from an internal database, it would be slower to get real txids for every record, so we get real txids only for clicked ones

**Comment by username1565** [comment]
Nice! Thanks.
