### ISSUE TITLE
How to config w8io on our own node ?

### ISSUE THREAD

**Issue by narmathamuthu** [deemru/w8io#7]
Hi team ,

I have done the this code configuration on my local system.

But i got blank page ( PFA ) . 

![Screenshot from 2019-10-19 17-44-37](https://user-images.githubusercontent.com/55826071/67146698-3c821c00-f2ab-11e9-9818-99a4d1e04836.png)

So how to config our node data base ? 

Please explain what we need do to done ?

**Comment by deemru** [comment]
Sorry, i didn't check working from scratch at last commits, there were some changes, it is fixed now.

## Installation

- `git clone https://github.com/deemru/w8io.git`
- `cd w8io`
- `composer update`
- (optional) edit `w8io_config.sample.php` (default set for TESTNET)
- `php w8io_updater.php`

## Running

- `php w8io_updater.php` must be running at background all the time (i use: `nohup php w8io_updater.php > /var/log/w8io_updater.log &`)
- your http server should route everything (except `jquery.js`) to `index.php`

**Comment by narmathamuthu** [comment]
Hi , 

I got issue when i run the command ( php w8io_updater.php )

PFA. 

![Screenshot from 2019-10-21 14-47-23](https://user-images.githubusercontent.com/55826071/67192813-de237d80-f411-11e9-815a-bc811b0edf92.png)

Can you please explain me.

**Comment by deemru** [comment]
You should cleanup and start from scratch: https://github.com/deemru/w8io/issues/7#issuecomment-544160042

**Comment by narmathamuthu** [comment]
Hi deemru , 

Okay Fine.

If possible to change the W8IO_NODES ?

Like our private node. 

Because i have done private node configuration.

**Comment by deemru** [comment]
> If possible to change the W8IO_NODES ?

Just make sure that everything is working properly in the default config.

Then make any changes according your needs.

**Comment by narmathamuthu** [comment]
Hi , 
Now i got response on terminal .

Response like  ( 2019.10.21 15:37:20    INFO: 2383 (transactions) ). 

But still now i got blank page. 

Can you please explain me what i am wrong. 

How to get the API functionality please ? 

PFA.

![Screenshot from 2019-10-21 15-40-35](https://user-images.githubusercontent.com/55826071/67196794-22fee280-f419-11e9-839c-e3bf19a03218.png)

**Comment by deemru** [comment]
> But still now i got blank page.

If HTTP routing is correctly set to `index.php` then you must check/edit W8IO_ROOT:
https://github.com/deemru/w8io/blob/7a09e84af7e66530ab028c72adca32bad1f406dd/w8io_config.sample.php#L12

For example if a site is located at http://127.0.0.1/w8io-test/ then W8IO_ROOT should be defined as: 
```php
define( 'W8IO_ROOT', '/w8io-test/' );
```

**Comment by narmathamuthu** [comment]
Hi we can't change W8IO_ROOT path. 

My Browser Link ( http://localhost/w8io/index.php/ ) 

Still now we got blank page, 

Can you please explain me? 

:cry:

**Comment by deemru** [comment]
> Hi we can't change W8IO_ROOT path.

Why you can not change W8IO_ROOT?

> Can you please explain me?

There is an error on your side.

If you provide your w8io and http server configs i can help.

**Comment by narmathamuthu** [comment]
@deemru 

Hi , kindly find the attachment. 

![Screenshot from 2019-10-21 18-13-26](https://user-images.githubusercontent.com/55826071/67206099-9f4ff080-f42e-11e9-8baf-96f9af642297.png)

![Screenshot from 2019-10-21 18-13-34](https://user-images.githubusercontent.com/55826071/67206104-a24ae100-f42e-11e9-88b3-748d49cfd443.png)

**Comment by deemru** [comment]
If you use W8IO_ROOT = '/php70/w8io/' then you should use http://localhost/php70/w8io/

**Comment by narmathamuthu** [comment]
Yes !!! .

But still now we got blank page. 

I got response only this link ( http://localhost/php70/w8io/tx/DPpPzGQ8X9h1zhXQ9rGAyvv594ECLFNksBHDFyyjoKkb ) . 
 
But we can't get any other response like matcher exchange history etc...


And also how to get this functionality in our local system ( https://api.testnet.wavesplatform.com/v0/transactions/exchange?matcher=3N8aZG6ZDfnh8YxS6aNcteobN8eXTWHaBBd&amountAsset=WAVES&priceAsset=DWgwcZTMhSvnyYCoWLRUXXSH1RSkzThXLJhww9gwkqdn&limit=1 ). With our node

**Comment by deemru** [comment]
> But we can't get any other response like matcher exchange history etc...

Got it, check the databases permissions at /php70/w8io/var/db/

Try: ```chmod -R 777 /var/www/html/php70/w8io/var/```

**Comment by narmathamuthu** [comment]
@deemru  Wow its showing result now. 

We need to change network configuration using this ( define( 'W8IO_NETWORK', 'T' ); ) . Its correct ? 

I have another one doubt how to build this functionality using our node (  https://api.testnet.wavesplatform.com/v0/transactions/exchange?matcher=3N8aZG6ZDfnh8YxS6aNcteobN8eXTWHaBBd&amountAsset=WAVES&priceAsset=DWgwcZTMhSvnyYCoWLRUXXSH1RSkzThXLJhww9gwkqdn&limit=1 )

**Comment by deemru** [comment]
> We need to change network configuration using this ( define( 'W8IO_NETWORK', 'T' ); ) . Its correct ?

If your chainId is 'T' then yes.

> I have another one doubt how to build this functionality using our node ( https://api.testnet.wavesplatform.com/v0/transactions/exchange?matcher=3N8aZG6ZDfnh8YxS6aNcteobN8eXTWHaBBd&amountAsset=WAVES&priceAsset=DWgwcZTMhSvnyYCoWLRUXXSH1RSkzThXLJhww9gwkqdn&limit=1 )

It is not related to w8io.

**Comment by narmathamuthu** [comment]
@deemru 

If possible to get the all response in JSON format ?

**Comment by deemru** [comment]
will be in next version

**Comment by narmathamuthu** [comment]
Okay thank you so much.
Once released next version kindly let us know. 
We are waiting :)
